export const BLOG_POST_REPOSITORY_SRV = 'BLOG_POST_REPOSITORY_SRV';
export const BLOG_POST_ACCESS_CONTROL_SRV = 'BLOG_POST_ACCESS_CONTROL_SRV';
export const BLOG_POST_SRV = 'BLOG_POST_SRV';
export const BLOG_POST_PUBLISHING_SRV = 'BLOG_POST_PUBLISHING_SRV';
export const BLOG_POST_SERIALIZER_SRV = 'BLOG_POST_SERIALIZER_SRV';
