// global modules
import cn from 'classnames';
import { Effect } from 'effect';
import type { Metadata } from 'next';
import { MainMenu } from '@repo/ui/main-menu';
import { Poppins, Roboto } from 'next/font/google';

// local modules
import { lightTheme as lightThemeCn } from './theme.module.scss';
import { getStringUrlParam, rscPage } from '~/src/rsc';

// =============================================================
//                     F O N T S
// =============================================================
const poppins = Poppins({ variable: '--title-font-family', weight: '700', subsets: ['latin'] });
const roboto = Roboto({ variable: '--general-font-family', weight: '400', subsets: ['latin'] });

// =============================================================
//                  M E T A D A T A
// =============================================================
export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const getUrlLocale = getStringUrlParam('locale');

export default rscPage(
  (props) => Effect.all({ locale: getUrlLocale(props) }),
  ({ locale, children }) => {
    return (
      <html lang={locale}>
        <body className={cn(lightThemeCn, poppins.variable, roboto.variable)}>
          <MainMenu />
          {children}
        </body>
      </html>
    );
  }
);
