// global modules
import { MainMenu } from '@bit-trove/ui/main-menu';
import type { Metadata } from 'next';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { ThemeProvider } from '@bit-trove/ui/theme-provider';
import { getMessages, getTranslations } from 'next-intl/server';
import { getNow, getTimeZone } from 'next-intl/server';

// local modules
import { Footer } from '~/components/footer';
import { layout as layoutCn } from './layout.module.scss';
import { PopupWatcher } from '~/components/popup-watcher';
import { Providers } from './providers';
import type { RSCLayoutProps } from '~/src/rsc';

// =============================================================
//                  M E T A D A T A
// =============================================================
export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Create Turborepo',
};

const getMainMenuProps = async () => {
  const t = await getTranslations();

  return {
    navigation: [
      { href: '/', name: t('home_page') },
      { href: '/blog', name: t('blogs_page') },
      { href: '/thoughts', name: t('thoughts_page') },
      { href: '/', name: t('tips_and_tricks_page') },
    ],

    buttons: [
      { icon: '/assets/search.svg', name: t('search_button'), onClick: () => {} },
      { icon: '/assets/burger.svg', name: t('menu'), onClick: () => {} },
    ],
  };
};

export default async function LocaleLayout(props: RSCLayoutProps) {
  const locale = props.params.locale;

  const [menuProps, timeZone, now, messages] = await Promise.all([
    getMainMenuProps(),
    getTimeZone({ locale }),
    getNow({ locale }),
    getMessages({ locale }),
  ]);

  return (
    <html lang={locale}>
      <body>
        <Providers locale={locale} messages={messages} now={now} timeZone={timeZone}>
          <ThemeProvider className={layoutCn}>
            <MainMenu {...menuProps} />
            <main>
              {props.children}
              <PopupWatcher locale={locale} />
            </main>
            <ThemeProvider dark>
              <Footer locale={locale} />
            </ThemeProvider>
          </ThemeProvider>

          <ReactQueryDevtools initialIsOpen={false} />
        </Providers>
      </body>
    </html>
  );
}
