// global modules
import cn from 'classnames';
import type { Metadata } from 'next';
import { MainMenu } from '@repo/ui/main-menu';
import { Poppins, Roboto } from 'next/font/google';
import { getTimeZone, getNow } from 'next-intl/server';
import { getMessages, getTranslations } from 'next-intl/server';

// local modules
import { Providers } from './providers';
import { Footer } from '~/components/footer';
import type { RSCLayoutProps } from '~/src/rsc';
import { layout as layoutCn } from './layout.module.scss';
import { ThemeProvider } from '~/components/theme-provider';

// =============================================================
//                     F O N T S
// =============================================================
const poppins = Poppins({
  variable: '--title-font-family',
  weight: ['400', '700'],
  subsets: ['latin'],
});
const roboto = Roboto({ variable: '--general-font-family', weight: '400', subsets: ['latin'] });

// =============================================================
//                  M E T A D A T A
// =============================================================
export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const getMainMenuProps = async () => {
  const t = await getTranslations();

  return {
    navigation: [
      { name: t('home_page'), href: '/' },
      { name: t('blogs_page'), href: '/blog' },
      { name: t('tutorials_page'), href: '/' },
      { name: t('tips_and_tricks_page'), href: '/' },
    ],
    buttons: [
      { icon: '/assets/search.svg', name: t('search_button'), onClick: () => {} },
      { icon: '/assets/burger.svg', name: t('menu'), onClick: () => {} },
    ],
  };
};

export default async function LocaleLayout(props: RSCLayoutProps) {
  const locale = props.params.locale;

  const [menuProps, timeZone, now, messages] = await Promise.all([
    getMainMenuProps(),
    getTimeZone({ locale }),
    getNow({ locale }),
    getMessages({ locale }),
  ]);

  return (
    <html lang={locale}>
      <body className={cn(poppins.variable, roboto.variable)}>
        <Providers locale={locale} timeZone={timeZone} now={now} messages={messages}>
          <ThemeProvider className={layoutCn}>
            <MainMenu {...menuProps} />
            <div>{props.children}</div>
            <ThemeProvider dark>
              <Footer locale={locale} />
            </ThemeProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
