export const TUTORIAL_REPOSITORY_SRV = 'TUTORIAL_REPOSITORY_SRV';
export const TUTORIAL_ACCESS_CONTROL_SRV = 'TUTORIAL_ACCESS_CONTROL_SRV';
export const TUTORIAL_SRV = 'TUTORIAL_SRV';
export const TUTORIAL_PUBLISHING_SRV = 'TUTORIAL_PUBLISHING_SRV';
export const TUTORIAL_SERIALIZER_SRV = 'TUTORIAL_SERIALIZER_SRV';
