import cn from 'classnames';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins, Roboto } from 'next/font/google';
import { lightTheme as lightThemeCn } from './theme.module.scss';

const poppins = Poppins({ variable: '--title-font-family', weight: '700', subsets: ['latin'] });
const roboto = Roboto({ variable: '--general-font-family', weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={cn(lightThemeCn, poppins.variable, roboto.variable)}>{children}</body>
    </html>
  );
}
