export const GUIDE_REPOSITORY_SRV = 'GUIDE_REPOSITORY_SRV';
export const GUIDE_ACCESS_CONTROL_SRV = 'GUIDE_ACCESS_CONTROL_SRV';
export const GUIDE_SRV = 'GUIDE_SRV';
export const GUIDE_PUBLISHING_SRV = 'GUIDE_PUBLISHING_SRV';
export const GUIDE_SERIALIZER_SRV = 'GUIDE_SERIALIZER_SRV';
