export const blogPostHorizontalPreview: string;
export const coverHolder: string;
export const viewsCount: string;
export const title: string;
export const badges: string;
export const text: string;
export const coverRestrictor: string;
export const pending: string;
export const pendingLine: string;
