export const avatar: string;
export const xxs: string;
export const xs: string;
export const sm: string;
export const md: string;
export const lg: string;
export const xl: string;
export const xxl: string;
export const img: string;
