export const ARTICLE_ACCESS_CONTROL_SRV = 'ARTICLE_ACCESS_CONTROL_SRV';
export const ARTICLE_PUBLISHING_SRV = 'ARTICLE_PUBLISHING_SRV';
export const ARTICLE_SERIALIZER_SRV = 'ARTICLE_SERIALIZER_SRV';
